---
version: 1

build_arg_defaults:
  ##EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-21/ee-minimal-rhel8:latest'
  ##EE_BASE_IMAGE: 'quay.io/redhat_emp1/ee-ansible-ssa:1.3.0.19'
  ##EE_BASE_IMAGE: 'quay.io/redhat_emp1/ee-ansible-ssa:unstable'
  EE_BASE_IMAGE: 'quay.io/redhat_emp1/ee-ansible-ssa:2.0.0.1'

ansible_config: 'ansible.cfg'


dependencies:
  galaxy: requirements.yml
  python: requirements.txt

additional_build_steps:
  append:
    - ENV PYTHONPATH=/usr/libexec/platform-python

