---
version: 1.5

build_arg_defaults:
  #EE_BASE_IMAGE: 'quay.io/redhat_emp1/ee-ansible-ssa:2.5.0.1'
  EE_BASE_IMAGE: registry.redhat.io/ansible-automation-platform-23/ee-minimal-rhel8:1.0.0-294
  EE_BUILDER_IMAGE: registry.redhat.io/ansible-automation-platform-23/ansible-builder-rhel8

ansible_config: 'ansible.cfg'
#ansible_config: /home/gitlab-runner/.ansible.cfg


dependencies:
  system: bindep.txt
  python: requirements.txt
  galaxy: requirements.yml

additional_build_steps:
  append:
    - ENV PYTHONPATH=/usr/libexec/platform-python
