---
collections:
  - name: hpe.oneview
  - name: community.general
    version: 6.1.0
  - name: vmware.vmware_rest
  - name: ansible.controller
    version: 4.1.2
#  - name: ansible.netcommon
#    version: 3.1.1
#  - name: ansible.network
#    version: 1.2.0
  - name: ansible.posix
    version: 1.4.0
#  - name: ansible.security
#    version: 1.0.0
  - name: ansible.utils
    version: 2.6.1
#  - name: ansible.windows
#    version: 1.12.0
#  - name: ansible.yang
#    version: 1.0.0
#  - name: redhat.rhel_system_roles
#    version: 1.16.2
  - name: community.vmware
    version: 3.2.0
